apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agro-apps

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - ingressroute.yaml

labels:
  - pairs:
      project: tc-agro-solutions
      managed-by: argocd
    includeSelectors: true
