apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agro-apps

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

commonLabels:
  project: tc-agro-solutions
  managed-by: argocd
