apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend
  - ../../base/identity
  - identity-hpa.yaml

# Strategic merge patch for identity deployment replicas
patchesStrategicMerge:
  - identity-patch.yaml
