apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend
  - ../../base/identity
  - ../../base/farm
  - frontend-hpa.yaml
  - identity-hpa.yaml
  - farm-hpa.yaml
