apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/frontend
  - ../../base/identity

# DEV-specific patches for resource tuning
patchesStrategicMerge:
  - identity-patch.yaml

resources:
  - identity-hpa.yaml
