apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/frontend
  - ../../base/identity
  - identity-hpa.yaml

# DEV-specific patches for resource tuning
patches:
  - path: identity-patch.yaml
    target:
      kind: Deployment
      name: identity-api
